version: '3.1'

services:
  fediuni:
    build:
      context: .
    container_name: fediuni-xyz
    ports:
      - 8080:8080
    secrets:
      - config
    deploy:
      restart_policy:
        condition: on-failure

secrets:
  config:
    file: config.yaml
