version: '0.0'

services:
  fediuni:
    build:
      context: .
    container_name: fediuni-xyz
    ports:
      - 80:8080
    environment:
      - MONGO_URI=${MONGO_URI}
      - FEDIUNI_URL=${FEDIUNI_URL}
    deploy:
      restart_policy:
        condition: on-failure